module.exports = {
  android: {
    edgeToEdgeEnabled: true,
    versionCode: 14,
    package: "com.pcelectronics.zentara",
    adaptiveIcon: {
      foregroundImage: "./assets/zentara_icon_clean.png",
      backgroundColor: "#ffffff",
    },
    allowBackup: undefined,
    permissions: undefined,
    blockedPermissions: undefined,
  },
  assetBundlePatterns: ["**/*"],
  experiments: { typedRoutes: true, tsconfigPaths: true },
  icon: "./assets/zentara_icon_clean.png",
  ios: {
    supportsTablet: false,
    buildNumber: "14",
    bundleIdentifier: "com.pcelectronics.zentara",
    usesAppleSignIn: false,
    requireFullScreen: false,
    associatedDomains: undefined,
    appStoreUrl: undefined,
    isTabletOnly: undefined,
    infoPlist: {
      NSCameraUsageDescription: undefined,
      NSMicrophoneUsageDescription: undefined,
      NSPhotoLibraryUsageDescription: undefined,
      NSPhotoLibraryAddUsageDescription: undefined,
      NSLocationWhenInUseUsageDescription: undefined,
      NSLocationAlwaysUsageDescription: undefined,
      NSContactsUsageDescription: undefined,
      NSCalendarsUsageDescription: undefined,
      NSRemindersUsageDescription: undefined,
      NSMotionUsageDescription: undefined,
      NSFaceIDUsageDescription: undefined,
      NSSpeechRecognitionUsageDescription: undefined,
      NSBluetoothPeripheralUsageDescription: undefined,
      NSAppleMusicUsageDescription: undefined,
      NSUserTrackingUsageDescription: undefined,
    },
    privacyManifests: undefined,
    bitcode: undefined,
  },
  name: "Zentara",
  orientation: "portrait",
  plugins: [
    "expo-font",
    "expo-asset",
    "expo-video",
    "expo-web-browser",
    "expo-notifications",

    ["./plugins/withIosBuildFix"],

    [
      "expo-router",
      {
        origin: "https://ff28a34e3e.sandbox.draftbit.dev:5101",
        headOrigin: "https://ff28a34e3e.sandbox.draftbit.dev:5100",
      },
    ],
    ["./plugins/draftbit-auto-launch-url-plugin"],
  ],

  scheme: "new-app",
  slug: "new-app",
  splash: {
    image: "./assets/images/splash.png",
    resizeMode: "contain",
    backgroundColor: "#ffffff",
  },
  userInterfaceStyle: "automatic",
  version: "1.0.13",
  web: {
    bundler: "metro",
    output: "single",
    favicon: "./assets/images/favicon.png",
    themeColor: undefined,
    name: undefined,
    shortName: undefined,
    lang: undefined,
    backgroundColor: undefined,
    description: undefined,
    orientation: undefined,
    startUrl: undefined,
  },
  platforms: ["ios", "android", "web"],
  description: undefined,
  locales: undefined,
  extra: undefined,
  jsEngine: undefined,
  notification: {
    icon: undefined,
    color: undefined,
    iosDisplayInForeground: false,
    androidMode: "default",
    androidCollapsedTitle: undefined,
  },
};
